version: '2'

services:
  rabbitmq:
    build: rabbitmq
    ports:
      - 5671:5671
      - 5672:5672
      - 8080:8080
      - 15671:15671
      - 15672:15672

  bootstrap:
    build: bootstrap
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
      - EXCHANGE_NAME=logs
      - EXCHANGE_TYPE=x-consistent-hash
      - QUEUE_TYPE=quorum
      - BINDING_KEY=10
    depends_on:
      - rabbitmq
